### ISSUE TITLE
Inicializar un repositorio y un procedimiento para que todos los miembros del equipo puedan levantar el ambiente de desarrollo.

### ISSUE THREAD

**Issue by ingenieriacreativads3** [arquitecturas-moviles-2019/cursos-app#1]
La idea es poder realizar un proyecto nuevo en Android Studio, construyendo en paralelo un tutorial, con el objetivo de que todos los miembros puedan levantar el ambiente de desarrollo individualmente, como para saber quien lo pudo levantar y esta en codiciones de codificar, quien puede emular la aplicación, etc.

**Comment by fmoreyra** [comment]
Por mi parte lo pude levantar y todo de 10. Aconsejaría usar el debugger del teléfono antes que la VM (por lo menos a mí se me hace pesado, android studio ya es pesadón jajaja)

**Comment by ingenieriacreativads3** [comment]
Pudiste? pushealo, en el repo del proyecto, para que todos tengamos el mismo.

**Comment by ingenieriacreativads3** [comment]
> Por mi parte lo pude levantar y todo de 10. Aconsejaría usar el debugger del teléfono antes que la VM (por lo menos a mí se me hace pesado, android studio ya es pesadón jajaja)

Pudiste? Pushealo en el repo del proyecto, para ver si todos podemos levantar el mismo ambiente.

**Comment by DavidAlonso97** [comment]
Ya estan los archivos listos para clonar.
