### ISSUE TITLE
HU2

### ISSUE THREAD

**Issue by santiagobarra** [arquitecturas-moviles-2019/cursos-app#10]
COMO usuario
QUIERO poder ingresar a la app ingresando usuario y contraseña
PARA poder acceder a la app.

Criterio de Aceptación:	
DADO un usuario que todavía no inició sesión en la app
CUANDO	intenta visualizar los eventos y cursos	
ENTONCES debe completar su email y contraseña y validar que sean correctos

**Comment by SofiGaggi** [comment]
![2](https://user-images.githubusercontent.com/22307277/56214909-1e560d80-6035-11e9-86b6-911ab42a7e87.PNG)
