### ISSUE TITLE
HU5

### ISSUE THREAD

**Issue by Yoha95** [arquitecturas-moviles-2019/cursos-app#11]
COMO usuario
QUIERO poder visualizar los datos del curso (ubicacion, fecha, descripcion)  (desde eventos o mis cursos)	
PARA	saber cuando y donde debo asistir a las clases 	

Criterio de Aceptación:	
DADO un usuario que desea ver los datos de un curso	
CUANDO	hace click en el curso (desde eventos o mis cursos)	
ENTONCES	se le mostrarará el detalle del curso seleccionado

**Comment by SofiGaggi** [comment]
![5](https://user-images.githubusercontent.com/22307277/56215386-f9ae6580-6035-11e9-8ae5-dc98817f955a.PNG)
