### ISSUE TITLE
Encontrar una manera de mejorar las caracteristicas de ramificacion en repositorio, para evitar los problemas de superpocision de codigo, duplicacion de codigo, y demas problemas acerca de codificacion en paralelo.

### ISSUE THREAD

**Issue by ingenieriacreativads3** [arquitecturas-moviles-2019/cursos-app#2]
Los problemas que se pretenden resolver es la comunicacion del trabajo en paralelo. Una forma de resolverlo es ramificando el proyecto. Esto es posible para cuando las tareas estan bien divididas, para cuando el proyecto es grande, y hay una buena organizacion de proyecto, 3 cualidades que carecemos, como grupo. Otra alternativa posible es compartir el proyecto en tiempo real, y que sea posible que una persona se agregue al link de master, y empiece a codear en la maquina de otro integrante. Es un plguin que probe mucho en vs code, pero no si existira algo parecido en android studio. pero es una caracteristica que funciona con grupos muy chicos, que codean en paralelo, sin organizacion alguna para el proyecto. codear y arreglar. caracteristicas que tampoco tenemos, porque somos muchos, y tenemos un minimo de organizacion. la idea es encontrar un punto medio que resuelva la comunicacion en la programacion en paralelo, en un grupo de trabajo donde no es tan buena la organizacion, la division de tareas no es tan clara, y el grupo es grande.

**Comment by emi310397** [comment]
Creo que no debería haber problemas si trabajamos con ramas como corresponde. Es decir, con ramas puntuales. No trabajar todos en master porque si no, ahí si sería un lío.
https://git-scm.com/book/es/v1/Git-en-entornos-distribuidos-Gestionando-un-proyecto

**Comment by ingenieriacreativads3** [comment]
me parece que es muy chico el proyecto, como para estar haciendo muchas ramas. incluso determinamos un solo sprint con todas las histories incluidas.

**Comment by emi310397** [comment]
Con más razón, no deberían haber muchos commits como para perderse. Serían muchas ramas quizás, más para la parte de desarrollo y testing, pero con pocos commits y más consistentes. No se, me parece a mi...

**Comment by fmoreyra** [comment]
+1 a emi

**Comment by ingenieriacreativads3** [comment]
Abri un pull en slack/dev facu. Creo que esto lo deberian decidir ustedes.
