### ISSUE TITLE
HU3

### ISSUE THREAD

**Issue by Yoha95** [arquitecturas-moviles-2019/cursos-app#7]
QUIERO poder visualizar los eventos proximos y en curso 	
PARA tener conocimiento de los mismos	

Criterio de Aceptación:	
DADO un usuario que desea ver los eventos 	
CUANDO	hace click en la pestaña eventos	
ENTONCES se le mostrará en pantalla el listado de eventos

**Comment by SofiGaggi** [comment]
![3](https://user-images.githubusercontent.com/22307277/56215072-6c6b1100-6035-11e9-998d-d96039e94788.PNG)
